### ISSUE TITLE
Time complexities?

### ISSUE THREAD

**Issue by thomasharmon808** [fitzgen/associative-cache#1]
Hi, I was looking for something exactly like your crate for a class project. The only thing that I was wondering was the (amortized) time complexity of `get`, `get_mut`, `insert`, and `remove`? Is there significant overhead to using this associative cache over a regular hash map?

**Comment by thomasharmon808** [comment]
Also, I looked through your crate more and also the source code to figure out how the `LRUReplacement` would work without `.get` taking and `&mut self` and I gotta say this crate is pretty sick! Thank you very much for publishing it!

**Comment by fitzgen** [comment]
> The only thing that I was wondering was the (amortized) time complexity of `get`, `get_mut`, `insert`, and `remove`?

They should all be O(1).

> Is there significant overhead to using this associative cache over a regular hash map?

They are sort of for different use cases. A hash map isn't great as a fixed-size cache because evicting an old entry when inserting an unrelated new entry at full capacity is hard to do well.

Look up might be a bit faster in Rust's std hash maps because they've seen a bunch of perf work, but also because an associative cache has to check each potential location where the value might be stored. I suspect that in most cases, a hash map isn't doing much probing, and hashbrown is quite optimized for probing when it does have to do it: https://gankra.github.io/blah/hashbrown-insert/

> Thank you very much for publishing it!

You're welcome!

**Comment by thomasharmon808** [comment]
Thanks again! I appreciate the response. Have a nice day :D!
